const TagConstants = {
  RECIVE_TAGGED_SONGS: "RECEIVE_TAGGED_SONGS",
  RECIVE_TAG: "RECEIVE_TAG",
  REMOVE_TAG: "REMOVE_TAG",
  ADD_TAG: "ADD_TAG",
  RESET_TAGS: "RESET_TAGS"
};
module.exports = TagConstants;
